// apps/mobile/app.config.js
//
// Dynamic Expo config for White Label.
// Reads the active client from env (CLIENT, then EAS_BUILD_PROFILE, then current.json),
// loads branding/<Client>/.env into process.env, merges branding/<Client>/app.config.json,
// and exposes theme + business id via expo.extra so the runtime can read them via Constants.
//
// IMPORTANT: This file runs in Node (NOT in the JS bundle). Do not import RN code here.

const fs = require("node:fs");
const path = require("node:path");

const projectRoot = __dirname;
const monorepoRoot = path.resolve(projectRoot, "..", "..");
const brandingRoot = path.join(monorepoRoot, "branding");

function readJsonSafe(file, fallback = null) {
  try {
    if (!fs.existsSync(file)) return fallback;
    return JSON.parse(fs.readFileSync(file, "utf8"));
  } catch {
    return fallback;
  }
}

function loadEnvFile(envPath) {
  if (!fs.existsSync(envPath)) return false;
  const text = fs.readFileSync(envPath, "utf8");
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const idx = line.indexOf("=");
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    let value = line.slice(idx + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (process.env[key] === undefined) {
      process.env[key] = value;
    }
  }
  return true;
}

function resolveClient() {
  if (process.env.CLIENT && process.env.CLIENT.trim()) return process.env.CLIENT.trim();

  if (process.env.EAS_BUILD_PROFILE && process.env.EAS_BUILD_PROFILE.trim()) {
    return process.env.EAS_BUILD_PROFILE.trim();
  }

  const current = readJsonSafe(path.join(brandingRoot, "current.json"));
  if (current?.client) return current.client;

  return "Default";
}

function safeRequireExpo() {
  try {
    return require("expo-constants");
  } catch {
    return null;
  }
}

function buildConfig({ config }) {
  const client = resolveClient();
  const clientDir = path.join(brandingRoot, client);

  if (!fs.existsSync(clientDir)) {
    throw new Error(
      `[white-label] branding/${client}/ does not exist. ` +
        `Set CLIENT to a valid client (one of branding/<Client>/) or run scripts/add-client.mjs ${client}`
    );
  }

  const envPath = path.join(clientDir, ".env");
  if (loadEnvFile(envPath)) {
    console.log(`✅ Loaded environment from: branding/${client}/.env`);
  } else {
    console.warn(`⚠️  branding/${client}/.env not found`);
  }

  const appOverrides = readJsonSafe(path.join(clientDir, "app.config.json"), {});
  const theme = readJsonSafe(path.join(clientDir, "theme.json"), {});

  if (!process.env.EAS_BUILD) {
    const fsOut = path.join(brandingRoot, "current.json");
    fs.mkdirSync(path.dirname(fsOut), { recursive: true });
    fs.writeFileSync(
      fsOut,
      JSON.stringify(
        {
          client,
          updatedAt: new Date().toISOString(),
          note: "Auto-generated by app.config.js / scripts. Do not edit manually.",
        },
        null,
        2
      ) + "\n"
    );

    const tsOut = path.join(projectRoot, "src", "config", "currentClient.ts");
    fs.mkdirSync(path.dirname(tsOut), { recursive: true });
    fs.writeFileSync(
      tsOut,
      [
        "// AUTO-GENERATED by apps/mobile/app.config.js. Do not edit manually.",
        `export const CURRENT_CLIENT = ${JSON.stringify(client)} as const;`,
        "",
      ].join("\n")
    );
  }

  const iconAbs = path.join(clientDir, "icon.png");
  const splashAbs = path.join(clientDir, "splash.png");
  const adaptiveAbs = path.join(clientDir, "adaptive-icon.png");
  const faviconAbs = path.join(clientDir, "favicon.png");

  const iconPath = fs.existsSync(iconAbs) ? iconAbs : "./assets/icon.png";
  const splashPath = fs.existsSync(splashAbs) ? splashAbs : "./assets/splash-icon.png";
  const adaptivePath = fs.existsSync(adaptiveAbs) ? adaptiveAbs : "./assets/adaptive-icon.png";
  const faviconPath = fs.existsSync(faviconAbs) ? faviconAbs : "./assets/favicon.png";

  const baseExtra = config?.extra ?? {};
  const baseIos = config?.ios ?? {};
  const baseAndroid = config?.android ?? {};

  const splashBg =
    appOverrides.splash?.backgroundColor ||
    theme?.colors?.background ||
    "#ffffff";

  const merged = {
    ...config,
    name: appOverrides.name || config?.name || "App",
    slug: appOverrides.slug || config?.slug || "my-project-mobile",
    scheme: appOverrides.scheme || config?.scheme,
    version: config?.version || "1.0.0",
    orientation: "portrait",
    icon: iconPath,
    userInterfaceStyle: "light",
    newArchEnabled: true,
    splash: {
      image: splashPath,
      resizeMode: appOverrides.splash?.resizeMode || "contain",
      backgroundColor: splashBg,
    },
    ios: {
      ...baseIos,
      ...(appOverrides.ios || {}),
      bundleIdentifier:
        appOverrides.ios?.bundleIdentifier || baseIos.bundleIdentifier,
      supportsTablet:
        appOverrides.ios?.supportsTablet ?? baseIos.supportsTablet ?? true,
    },
    android: {
      ...baseAndroid,
      ...(appOverrides.android || {}),
      package: appOverrides.android?.package || baseAndroid.package,
      adaptiveIcon: {
        foregroundImage: adaptivePath,
        backgroundColor:
          appOverrides.android?.adaptiveIcon?.backgroundColor || splashBg,
      },
      edgeToEdgeEnabled: true,
      predictiveBackGestureEnabled: false,
    },
    web: {
      favicon: faviconPath,
    },
    plugins: [
      "expo-router",
      [
        "expo-notifications",
        {
          sounds: [],
          mode: "production",
        },
      ],
      [
        "expo-image-picker",
        {
          photosPermission:
            "האפליקציה צריכה גישה לגלריה כדי להעלות את לוגו העסק.",
        },
      ],
      ...(appOverrides.extraPlugins || []),
    ],
    extra: {
      ...baseExtra,
      CLIENT: client,
      BUSINESS_ID:
        process.env.BUSINESS_ID || process.env.EXPO_PUBLIC_BUSINESS_ID || "",
      EXPO_PUBLIC_SUPABASE_URL: process.env.EXPO_PUBLIC_SUPABASE_URL ?? "",
      EXPO_PUBLIC_SUPABASE_ANON_KEY: process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY ?? "",
      EXPO_PUBLIC_WEB_API_ORIGIN: process.env.EXPO_PUBLIC_WEB_API_ORIGIN ?? "",
      eas: {
        projectId:
          process.env.EXPO_PUBLIC_EAS_PROJECT_ID ||
          process.env.EAS_PROJECT_ID ||
          baseExtra?.eas?.projectId ||
          "",
      },
      theme,
    },
  };

  console.log(`✅ Loaded config for client: ${client}`);
  console.log(`   slug=${merged.slug}  scheme=${merged.scheme || "<none>"}`);

  return merged;
}

module.exports = (ctx) => buildConfig(ctx);

// Touch expo-constants so static analyzers don't tree-shake the import path warning.
safeRequireExpo();
