import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const __filename = fileURLToPath(import.meta.url);
export const __dirname = path.dirname(__filename);
export const repoRoot = path.resolve(__dirname, "..");
export const brandingRoot = path.join(repoRoot, "branding");
export const mobileRoot = path.join(repoRoot, "apps", "mobile");
export const webRoot = path.join(repoRoot, "apps", "web");

export function listClients() {
  if (!fs.existsSync(brandingRoot)) return [];
  return fs
    .readdirSync(brandingRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name);
}

export function brandingDir(client) {
  return path.join(brandingRoot, client);
}

export function assertClientExists(client) {
  if (!client) {
    throw new Error("Missing client name. Usage: node scripts/<script>.mjs <Client>");
  }
  const dir = brandingDir(client);
  if (!fs.existsSync(dir)) {
    const available = listClients().join(", ") || "<none>";
    throw new Error(`Branding folder not found: ${dir}\nAvailable clients: ${available}`);
  }
  return dir;
}

export function readJson(filePath, fallback = null) {
  if (!fs.existsSync(filePath)) return fallback;
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

export function writeJson(filePath, data) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + "\n", "utf8");
}

export function copyDirSync(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirSync(srcPath, destPath);
    } else if (entry.isFile()) {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

export function rmDirSync(dir) {
  if (fs.existsSync(dir)) {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

export function writeCurrentClient(client) {
  const target = path.join(brandingRoot, "current.json");
  writeJson(target, {
    client,
    updatedAt: new Date().toISOString(),
    note: "Auto-generated by scripts/. Do not edit manually.",
  });
  return target;
}

export function readCurrentClient() {
  const target = path.join(brandingRoot, "current.json");
  const data = readJson(target);
  return data?.client ?? null;
}
