#!/usr/bin/env node
/**
 * scripts/switch-client.mjs <Client>
 *
 * Sets the active client for local development:
 *   - writes branding/current.json
 *   - syncs branding/<Client>/ assets to apps/web/public/branding/current/
 *   - regenerates apps/mobile/src/config/currentClient.ts
 *
 * For mobile, switching is mostly about the auto-generated currentClient.ts
 * (app.config.js still picks up CLIENT env at runtime).
 *
 * For web, public/branding/current/ exposes static assets (logo, favicon, splash)
 * to the browser regardless of which client is active.
 */
import fs from "node:fs";
import path from "node:path";
import {
  assertClientExists,
  brandingDir,
  copyDirSync,
  listClients,
  mobileRoot,
  rmDirSync,
  webRoot,
  writeCurrentClient,
} from "./_common.mjs";

function main() {
  const client = process.argv[2];

  if (!client) {
    console.error("Usage: node scripts/switch-client.mjs <Client>");
    console.error("Available clients: " + (listClients().join(", ") || "<none>"));
    process.exit(1);
  }

  const dir = assertClientExists(client);

  writeCurrentClient(client);
  console.log(`✅ branding/current.json -> ${client}`);

  const webPublicTarget = path.join(webRoot, "public", "branding", "current");
  rmDirSync(webPublicTarget);
  fs.mkdirSync(webPublicTarget, { recursive: true });
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith(".env")) continue;
    if (entry.isFile()) {
      fs.copyFileSync(path.join(dir, entry.name), path.join(webPublicTarget, entry.name));
    }
  }
  console.log(`✅ Synced web public assets -> apps/web/public/branding/current/`);

  const mobileConfigDir = path.join(mobileRoot, "src", "config");
  fs.mkdirSync(mobileConfigDir, { recursive: true });
  const out = path.join(mobileConfigDir, "currentClient.ts");
  fs.writeFileSync(
    out,
    [
      "// AUTO-GENERATED by scripts/switch-client.mjs (and apps/mobile/app.config.js).",
      "// Do not edit manually.",
      `export const CURRENT_CLIENT = ${JSON.stringify(client)} as const;`,
      "",
    ].join("\n"),
    "utf8"
  );
  console.log(`✅ Wrote ${path.relative(process.cwd(), out)}`);

  console.log("");
  console.log(`Active client is now: ${client}`);
  console.log("Mobile dev:  npm run start:" + client);
  console.log("Web dev:     npm run start:web:" + client);
}

main();
